### ISSUE TITLE
May 31st Webinar (Advanced API testing: Best Practices and Automation Techniques)

### ISSUE THREAD

**Issue by Kcorb95** [Kcorb95/postman-devrel-marketing-tracker#37]
## Details:
**Title:** Advanced API testing: Best Practices and Automation Techniques
**Date:** May 31st
**AirTable:** [Link to Webinar's AirTable entry](https://airtable.com/appGc6tC949Vd1rrg/tblw94UqczzmKczhr/viwXxHGRsHNdtG2nA/recGIkopKsj7wM2PC?blocks=hide)

## Tasks:
- [ ] LinkedIn Event
- [x] Contentful / Events Page
- [ ] In-App Announcements
- [x] Forums Post
- [ ] Pinned Forum Banner
- [ ] Social Posts
- [ ] Marketing Newsletter
- [ ] Webinar Email List

## Notes:
Socials should be posted 2x / week. ~2 weeks out from event, bump to 3x / week.
Be sure to spread out days and timezones. Mix of mentioning hosts and not mentioning hosts.
Value gained over WHO.
