### ISSUE TITLE
April 5th Webinar (Unboxing What's New in Postman Q1)

### ISSUE THREAD

**Issue by Kcorb95** [Kcorb95/postman-devrel-marketing-tracker#5]
## Details:
**Title:** Unboxing What's New in Postman Q1 
**Date:** April 5th
**AirTable:** https://airtable.com/appGc6tC949Vd1rrg/tblw94UqczzmKczhr/viwXxHGRsHNdtG2nA/recg1VqMSMzIdOjLW?blocks=hide

## Tasks:
- [x] LinkedIn Event
- [x] Contentful / Events Page
- [x] In-App Announcements
- [x] Forums Post
- [x] Pinned Forum Banner
- [x] Social Posts
- [ ] Marketing Newsletter
- [x] Webinar Email List

## Notes:
Socials should be posted 2x / week. ~2 weeks out from event, bump to 3x / week.
Be sure to spread out days and timezones. Mix of mentioning hosts and not mentioning hosts.
Value gained over WHO.

**Comment by sjwhitman** [comment]
Added drafts of promotional to the Notion Social Media Calendar! More info coming in update email
