### ISSUE TITLE
April 26th Webinar (Postman: Introduction for Developers)

### ISSUE THREAD

**Issue by Kcorb95** [Kcorb95/postman-devrel-marketing-tracker#6]
## Details:
**Title:** Postman: Introduction for Developers
**Date:** April 26th
**AirTable:** https://airtable.com/appGc6tC949Vd1rrg/tblw94UqczzmKczhr/viwXxHGRsHNdtG2nA/recqn6D4DxDXe9Vbr?blocks=hide

## Tasks:
- [x] LinkedIn Event
- [x] Contentful / Events Page
- [x] In-App Announcements
- [x] Forums Post
- [x] Pinned Forum Banner
- [x] Social Posts
- [x] Marketing Newsletter
- [x] Webinar Email List

## Notes:
Socials should be posted 2x / week. ~2 weeks out from event, bump to 3x / week.
Be sure to spread out days and timezones. Mix of mentioning hosts and not mentioning hosts.
Value gained over WHO.
